name: weather_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.7
  geolocator: ^10.1.0
  cached_network_image: ^3.3.0
  google_sign_in: ^6.1.1
  pin_code_fields: ^8.0.1
  http: ^1.1.0 
  intl: ^0.18.1
  flutter: 
    sdk: flutter
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
        - assets/
